version: '3.2'
services:
  dockcheck-web:
    container_name: dockcheck-web
    image: 'ghcr.io/supermamon/dockcheck-web:local'
    restart: unless-stopped
    ports:
      - '8401:80'
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PAGE_TITLE=Dockcheck
      - WINDOW_TITLE=Dockcheck
      - CHECK_ON_LAUNCH=false
      - NOTIFY=true
      - NOTIFY_URLS=slack://sometoken1/sometoken2/sometoken3
      - EXCLUDE=nginx
